package com.example.mapper;

import com.example.model.Fence;

public interface FenceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fence
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fence
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    int insert(Fence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fence
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    int insertSelective(Fence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fence
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    Fence selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fence
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    int updateByPrimaryKeySelective(Fence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fence
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    int updateByPrimaryKey(Fence record);
}