package com.example.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import lombok.Data;

/**
 * fence
 * @author Tensorflow
 * @date 2020-09-06 20:34:40
 */
@ApiModel(value="com.example.model.Fence")
@Data
public class Fence {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence.id
     *
     * @mbg.generated Sun Sep 06 20:34:39 CST 2020
     */
    /**
     */
    @ApiModelProperty(value="")
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence.region_id
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     */
    @ApiModelProperty(value="")
    private Long regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence.create_user
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 创建用户
     */
    @ApiModelProperty(value="创建用户")
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence.name
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 电子围栏名称
     */
    @ApiModelProperty(value="电子围栏名称")
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence.type
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 1：矩形区域，2：多边形区域，3：圆形区域
     */
    @ApiModelProperty(value="1：矩形区域，2：多边形区域，3：圆形区域")
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence.car_name
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 车牌号
     */
    @ApiModelProperty(value="车牌号")
    private String carName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence.car_type
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 车辆类型
     */
    @ApiModelProperty(value="车辆类型")
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence.fence_info
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 电子围栏定位点信息
     */
    @ApiModelProperty(value="电子围栏定位点信息")
    private String fenceInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence.start_time
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 电子围栏有效开始时间
     */
    @ApiModelProperty(value="电子围栏有效开始时间")
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence.end_time
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 电子围栏有效结束时间
     */
    @ApiModelProperty(value="电子围栏有效结束时间")
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence.warning_type
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 0:不报警，1:报警
     */
    @ApiModelProperty(value="0:不报警，1:报警")
    private Boolean warningType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence.create_time
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 创建时间
     */
    @ApiModelProperty(value="创建时间")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence.update_time
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 更新时间
     */
    @ApiModelProperty(value="更新时间")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence.status
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 0 : 正常，1：禁止使用
     */
    @ApiModelProperty(value="0 : 正常，1：禁止使用")
    private Boolean status;
}