package com.example.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import lombok.Data;

/**
 * user
 * @author Tensorflow
 * @date 2020-09-06 20:34:40
 */
@ApiModel(value="com.example.model.User")
@Data
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     */
    @ApiModelProperty(value="")
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 用户名登陆账号
     */
    @ApiModelProperty(value="用户名登陆账号")
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 状态   0:删除, 3:正常使用，4:禁用，5:禁止登录
     */
    @ApiModelProperty(value="状态   0:删除, 3:正常使用，4:禁用，5:禁止登录")
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.region_id
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 用户单位id
     */
    @ApiModelProperty(value="用户单位id")
    private Long regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_time
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 用户登录时间
     */
    @ApiModelProperty(value="用户登录时间")
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 创建时间
     */
    @ApiModelProperty(value="创建时间")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_time
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     * 更新时间
     */
    @ApiModelProperty(value="更新时间")
    private Date updateTime;
}