package com.example.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value="com.example.model.UserKey")
public class UserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Host
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     */
    @ApiModelProperty(value="")
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.User
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     */
    @ApiModelProperty(value="")
    private String user;
}