package com.example.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value="com.example.model.UserWithBLOBs")
public class UserWithBLOBs extends User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ssl_cipher
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     */
    @ApiModelProperty(value="")
    private byte[] sslCipher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.x509_issuer
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     */
    @ApiModelProperty(value="")
    private byte[] x509Issuer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.x509_subject
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     */
    @ApiModelProperty(value="")
    private byte[] x509Subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.authentication_string
     *
     * @mbg.generated Sun Sep 06 20:34:40 CST 2020
     */
    /**
     */
    @ApiModelProperty(value="")
    private String authenticationString;
}